version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/typing_game
      - NEXTAUTH_URL=http://your-domain.com
      - NEXTAUTH_SECRET=your-nextauth-secret-value
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - typing_game_network

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-password
      - MYSQL_DATABASE=typing_game
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - typing_game_network
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - typing_game_network
    depends_on:
      - db

networks:
  typing_game_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
